# Generated by Django 3.2.5 on 2022-02-28 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hmsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='username',
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contactnumber',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
