# Generated by Django 3.2.5 on 2022-03-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0003_remove_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='userame',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
