# Generated by Django 3.2.5 on 2022-03-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0004_auto_20220302_0607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='userame',
            new_name='username',
        ),
    ]
