# Generated by Django 3.2.5 on 2022-03-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0007_appointment_cardiodocs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardioDocs',
            new_name='CardioDoc',
        ),
    ]
